Add Spotify and WhatsApp data
Linaro/works-on-woa pull request #15
Opened 2023-09-18 16:46 UTC by marcpems

adding WhatsApp, Spotify items, corresponding new categories and icons

2023-09-19 12:43 UTC, anthony-linaro requested changes
A quick initial pass

2023-09-19 12:43 UTC, anthony-linaro commented on src/content/categories/audio.md
This does not match with the category name given under spotify - it needs to either be "audio" under spotify, or this file need to be renamed to "music"

2023-09-19 12:43 UTC, anthony-linaro commented on src/content/categories/app.md
I think a better description would work here - are me meaning MS store apps here?

2023-09-19 12:43 UTC, anthony-linaro commented on src/content/projects/spotify.md
> +categories: [Music, App]
See above comment

2023-09-19 15:06 UTC, marcpems commented on src/content/projects/spotify.md
> +categories: [Music, App]
thx. I'll resolve these and update

2023-09-20 13:47 UTC, anthony-linaro requested changes
A few more changes to be made.

Also, please can you confirm the licensing for where you have sourced the logos from please?

2023-09-20 13:47 UTC, anthony-linaro commented on src/content/categories/msstore.md
> +name: msstore
This is supposed to be a human-readable label - "Microsoft Store" perhaps?

2023-09-20 13:47 UTC, anthony-linaro commented on src/content/projects/spotify.md
> +categories: [Audio, App, MSStore]
These need to be lower case

2023-09-20 13:47 UTC, anthony-linaro commented on src/content/projects/whatsapp.md
> +categories: [Comms, App, MSStore]
These need to be lower case

2023-09-20 16:14 UTC, pcolmer approved these changes

2023-09-20 16:22 UTC, pcolmer approved these changes

2023-09-20 16:22 UTC, merged