WEBDEV-1557
Linaro/works-on-woa pull request #33
Opened 2024-02-13 16:24 UTC by kenzo7664

Separate Astro Collections

2024-02-13 16:35 UTC, louisjmorgan requested changes
Looks good but you should use some kind of casing for variable names that combine multiple words. Please see the comments for details.

2024-02-13 16:35 UTC, louisjmorgan commented on src/components/Common/Footer.astro
I think you should use camelCase here like `projectsApplications` `projectsGames`,
or even just `applications` and `games` would probably be fine in this case

2024-02-13 16:35 UTC, louisjmorgan commented on src/components/Projects/ProjectDetails.astro
similarly, I would maybe rename the collections to either camelCase or kebab_case
kebab_case might work better for folder names, so applications_categories

2024-02-13 16:35 UTC, louisjmorgan commented on src/content/config.ts
use kebab_case here as well

2024-02-13 16:35 UTC, louisjmorgan commented on src/layouts/CategoryLayout.astro
kebab_case

2024-02-13 16:35 UTC, louisjmorgan commented on src/layouts/ProjectLayout.astro
kebab_case

2024-02-14 10:51 UTC, louismorgan-linaro approved these changes
Looks good now.

2024-02-14 10:53 UTC, pcolmer commented
As discussed, we are going to hold on merging these changes until we've had some data from Microsoft so that we can actually put some games in there rather than duplicating the application information.

2024-02-14 10:54 UTC, pcolmer commented
I've converted this to a draft to prevent it from being merged.

2024-03-05 09:14 UTC, pcolmer commented
Microsoft have replied now.

* Name is required
* Publisher is optional
* Compatibility status is required and must be one of Perfect, Playable, Runs, Unplayable
* Status description is optional
* Frame rate is optional and must be one of "less than 30 fps", "30-60 fps", "above 60 fps"
* Device configuration is optional
* OS Version is optional
* Date tested is required
* Game type is optional
* Additional notes is optional

Thanks.

2024-03-05 09:26 UTC, louismorgan-linaro commented
Yes you're right. I'll just copy this https://github.com/sst/sst/blob/master/examples/quickstart-astro/.gitignore

2024-03-05 11:18 UTC, pcolmer commented
As soon as the `.gitignore` file gets updated, I'm happy for this to be merged to staging.

2024-04-19 12:12 UTC, closed without merging